name: REUSE Compliance

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.toml"
      - "**/*.json"
      - "**/*.md"
      - "uv.lock"
      - "LICENSES/**"
      - "REUSE.toml"
      - ".github/workflows/reuse.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.toml"
      - "**/*.json"
      - "**/*.md"
      - "uv.lock"
      - "LICENSES/**"
      - "REUSE.toml"
      - ".github/workflows/reuse.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  reuse:
    name: reuse
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Check REUSE compliance
        uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6
